import { createBrowserRouter, Outlet, Navigate } from 'react-router-dom'
import { ROUTES } from './routes'
import { AppProviders } from './providers/AppProviders'

// MUI Layouts
import { PublicLayout, AuthLayout } from './layouts'

// Route components
import {
  HomeRoute,
  LoginRoute,
  RegisterRoute,
  AcceptInviteRoute,
  DashboardRoute,
  UsersRoute,
  CharactersRoute,
  CharacterRoute,
  CampaignsRoute,
  CampaignRoute,
  EncounterRoute,
  RulesRoute,
  PartyRoute,
  SessionsRoute,
  SessionRoute,
  MessagingRoute,
  WorldLayout,
  LocationsRoute,
  LocationRoute,
  NpcsRoute,
  NpcRoute,
  MonsterListRoute,
  MonsterDetailRoute,
  MonsterEditRoute,
  MonsterCreateRoute,
  EquipmentHubRoute,
  WeaponsListRoute,
  ArmorListRoute,
  GearListRoute,
  MagicItemsListRoute,
  WeaponDetailRoute,
  ArmorDetailRoute,
  GearDetailRoute,
  MagicItemDetailRoute,
  WeaponEditRoute,
  ArmorEditRoute,
  GearEditRoute,
  MagicItemEditRoute,
  WeaponCreateRoute,
  ArmorCreateRoute,
  GearCreateRoute,
  MagicItemCreateRoute,
  AdminGuard,
  EncounterGuard,
  ContentManageGuard,
  CampaignAdminInvitesRoute,
  CampaignAdminSettingsRoute,
  CampaignRulesetEditorRoute,
  ClassListRoute,
  ClassDetailRoute,
  ClassCreateRoute,
  ClassEditRoute,
  RaceListRoute,
  RaceDetailRoute,
  RaceCreateRoute,
  RaceEditRoute,
  SpellListRoute,
  SpellDetailRoute,
  SpellCreateRoute,
  SpellEditRoute,
  SkillProficiencyListRoute,
  SkillProficiencyDetailRoute,
  SkillProficiencyCreateRoute,
  SkillProficiencyEditRoute,
  NewCharacterRoute,
} from './routes/index'

function RootLayout() {
  return (
    <AppProviders>
      <Outlet />
    </AppProviders>
  )
}

export const router = createBrowserRouter([
  {
    element: <RootLayout />,
    children: [
      {
        element: <PublicLayout />,
        children: [
          { path: ROUTES.HOME, element: <HomeRoute /> },
          { path: ROUTES.LOGIN, element: <LoginRoute /> },
          { path: ROUTES.REGISTER, element: <RegisterRoute /> },
          { path: ROUTES.ACCEPT_INVITE, element: <AcceptInviteRoute /> },
        ],
      },
      {
        element: <AuthLayout />,
        children: [
          { path: ROUTES.DASHBOARD, element: <DashboardRoute /> },
          { path: ROUTES.USERS, element: <UsersRoute /> },
          { path: ROUTES.CHARACTERS, element: <CharactersRoute /> },
          { path: ROUTES.NEW_CHARACTER, element: <NewCharacterRoute /> },
          { path: ROUTES.CHARACTER, element: <CharacterRoute /> },
          { path: ROUTES.CAMPAIGNS, element: <CampaignsRoute /> },
          {
            path: ROUTES.CAMPAIGN,
            element: <CampaignRoute />,
            children: [
              {
                path: 'world',
                element: <WorldLayout />,
                children: [
                  { index: true, element: <Navigate to="locations" replace /> },
                  { path: 'equipment', element: <EquipmentHubRoute /> },
                  { path: 'equipment/weapons', element: <WeaponsListRoute /> },
                  { path: 'equipment/weapons/:weaponId', element: <WeaponDetailRoute /> },
                  { path: 'equipment/armor', element: <ArmorListRoute /> },
                  { path: 'equipment/armor/:armorId', element: <ArmorDetailRoute /> },
                  { path: 'equipment/gear', element: <GearListRoute /> },
                  { path: 'equipment/gear/:gearId', element: <GearDetailRoute /> },
                  { path: 'equipment/magic-items', element: <MagicItemsListRoute /> },
                  { path: 'equipment/magic-items/:magicItemId', element: <MagicItemDetailRoute /> },
                  { path: 'classes', element: <ClassListRoute /> },
                  { path: 'classes/:classId', element: <ClassDetailRoute /> },
                  { path: 'races', element: <RaceListRoute /> },
                  { path: 'races/:raceId', element: <RaceDetailRoute /> },
                  { path: 'locations', element: <LocationsRoute /> },
                  { path: 'locations/:locationId', element: <LocationRoute /> },
                  { path: 'npcs', element: <NpcsRoute /> },
                  { path: 'npcs/:npcId', element: <NpcRoute /> },
                  { path: 'monsters', element: <MonsterListRoute /> },
                  { path: 'monsters/:monsterId', element: <MonsterDetailRoute /> },
                  { path: 'spells', element: <SpellListRoute /> },
                  { path: 'spells/:spellId', element: <SpellDetailRoute /> },
                  { path: 'skill-proficiencies', element: <SkillProficiencyListRoute /> },
                  { path: 'skill-proficiencies/:skillProficiencyId', element: <SkillProficiencyDetailRoute /> },
                  {
                    element: <ContentManageGuard />,
                    children: [
                      { path: 'equipment/weapons/new', element: <WeaponCreateRoute /> },
                      { path: 'equipment/weapons/:weaponId/edit', element: <WeaponEditRoute /> },
                      { path: 'equipment/armor/new', element: <ArmorCreateRoute /> },
                      { path: 'equipment/armor/:armorId/edit', element: <ArmorEditRoute /> },
                      { path: 'equipment/gear/new', element: <GearCreateRoute /> },
                      { path: 'equipment/gear/:gearId/edit', element: <GearEditRoute /> },
                      { path: 'equipment/magic-items/new', element: <MagicItemCreateRoute /> },
                      { path: 'equipment/magic-items/:magicItemId/edit', element: <MagicItemEditRoute /> },
                      { path: 'classes/new', element: <ClassCreateRoute /> },
                      { path: 'classes/:classId/edit', element: <ClassEditRoute /> },
                      { path: 'races/new', element: <RaceCreateRoute /> },
                      { path: 'races/:raceId/edit', element: <RaceEditRoute /> },
                      { path: 'monsters/new', element: <MonsterCreateRoute /> },
                      { path: 'monsters/:monsterId/edit', element: <MonsterEditRoute /> },
                      { path: 'spells/new', element: <SpellCreateRoute /> },
                      { path: 'spells/:spellId/edit', element: <SpellEditRoute /> },
                      { path: 'skill-proficiencies/new', element: <SkillProficiencyCreateRoute /> },
                      { path: 'skill-proficiencies/:skillProficiencyId/edit', element: <SkillProficiencyEditRoute /> },
                    ],
                  },
                ],
              },
              { path: 'sessions', element: <SessionsRoute /> },
              { path: 'sessions/:sessionId', element: <SessionRoute /> },
              { path: 'messages', element: <MessagingRoute /> },
              { path: 'messages/:conversationId', element: <MessagingRoute /> },
              { path: 'party', element: <PartyRoute /> },
              { path: 'rules', element: <RulesRoute /> },
              {
                element: <EncounterGuard />,
                children: [{ path: 'encounter', element: <EncounterRoute /> }],
              },
              {
                path: 'admin',
                element: <AdminGuard />,
                children: [
                  { path: 'invites', element: <CampaignAdminInvitesRoute /> },
                  { path: 'settings', element: <CampaignAdminSettingsRoute /> },
                  { path: 'ruleset', element: <CampaignRulesetEditorRoute /> },
                ],
              },
            ],
          },
          // { path: ROUTES.INVITE, element: <InviteRoute /> },
          // { path: ROUTES.ACCOUNT_SETTINGS, element: <AccountSettingsRoute /> },
          // {
          //   path: ROUTES.ADMIN,
          //   element: <AdminGuard />,
          //   children: [
          //     {
          //       element: <CampaignAdminRoute />,
          //       children: [
          //         { index: true, element: <Navigate to={ROUTES.ADMIN_INVITES} replace /> },
          //         { path: 'invites', element: <CampaignAdminInvitesRoute /> },
          //         { path: 'settings', element: <CampaignAdminSettingsRoute /> },
          //         { path: 'ruleset', element: <CampaignRulesetEditorRoute /> },
          //       ],
          //     },
          //   ],
          // },
        ],
      },
    ],
  },
])
