export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ACCEPT_INVITE: '/accept-invite',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  CHARACTERS: '/characters',
  NEW_CHARACTER: '/characters/new',
  CHARACTER: '/characters/:id',
  CAMPAIGNS: '/campaigns',
  ADMIN: '/admin',
  ACCOUNT: '/account',
  ACCOUNT_SETTINGS: '/account/settings',
  // Campaign scoped
  CAMPAIGN: '/campaigns/:id',
  CAMPAIGN_ADMIN_INVITES: '/campaigns/:id/admin/invites',
  CAMPAIGN_ADMIN_SETTINGS: '/campaigns/:id/admin/settings',
  CAMPAIGN_ADMIN_RULESET: '/campaigns/:id/admin/ruleset',
  /**
   * Encounter Simulator (dev/testing combat). Path segment `encounter` is kept for stability.
   * Not the future player-facing GameSession live-play surface.
   */
  CAMPAIGN_ENCOUNTER: '/campaigns/:id/encounter',
  CAMPAIGN_ENCOUNTER_SETUP: '/campaigns/:id/encounter/setup',
  CAMPAIGN_ENCOUNTER_ACTIVE: '/campaigns/:id/encounter/active',
  CAMPAIGN_RULES: '/campaigns/:id/rules',
  CAMPAIGN_PARTY: '/campaigns/:id/party',
  INVITE: '/invites/:inviteId',
  SESSIONS: '/campaigns/:id/sessions',
  SESSION: '/campaigns/:id/sessions/:sessionId',
  /**
   * Live-play GameSession (player-facing container). Distinct from calendar `SESSIONS` and
   * Encounter Simulator (`CAMPAIGN_ENCOUNTER`).
   */
  CAMPAIGN_GAME_SESSIONS: '/campaigns/:id/game-sessions',
  CAMPAIGN_GAME_SESSION: '/campaigns/:id/game-sessions/:gameSessionId',
  CAMPAIGN_GAME_SESSION_LOBBY: '/campaigns/:id/game-sessions/:gameSessionId/lobby',
  CAMPAIGN_GAME_SESSION_SETUP: '/campaigns/:id/game-sessions/:gameSessionId/setup',
  CAMPAIGN_GAME_SESSION_PLAY: '/campaigns/:id/game-sessions/:gameSessionId/play',
  MESSAGING: '/campaigns/:id/messages',
  MESSAGING_CONVERSATION: '/campaigns/:id/messages/:conversationId',
  WORLD: '/campaigns/:id/world',
  WORLD_LOCATIONS: '/campaigns/:id/world/locations',
  WORLD_LOCATION: '/campaigns/:id/world/locations/:locationId',
  WORLD_LOCATION_NEW: '/campaigns/:id/world/locations/new',
  WORLD_LOCATION_EDIT: '/campaigns/:id/world/locations/:locationId/edit',
  WORLD_NPCS: '/campaigns/:id/world/npcs',
  WORLD_NPC: '/campaigns/:id/world/npcs/:npcId',
  WORLD_MONSTERS: '/campaigns/:id/world/monsters',
  WORLD_MONSTER: '/campaigns/:id/world/monsters/:monsterId',
  WORLD_SKILL_PROFICIENCIES: '/campaigns/:id/world/skill-proficiencies',
  WORLD_SPELLS: '/campaigns/:id/world/spells',
  WORLD_SPELL: '/campaigns/:id/world/spells/:spellId',
  WORLD_SKILL_PROFICIENCY_NEW: '/campaigns/:id/world/skill-proficiencies/new',
  WORLD_SKILL_PROFICIENCY: '/campaigns/:id/world/skill-proficiencies/:skillProficiencyId',
  WORLD_SKILL_PROFICIENCY_EDIT: '/campaigns/:id/world/skill-proficiencies/:skillProficiencyId/edit',
  WORLD_EQUIPMENT: '/campaigns/:id/world/equipment',
  WORLD_EQUIPMENT_DETAILS: '/campaigns/:id/world/equipment/:equipmentId',
  WORLD_WEAPONS: '/campaigns/:id/world/equipment/weapons',
  WORLD_WEAPON_NEW: '/campaigns/:id/world/equipment/weapons/new',
  WORLD_WEAPON: '/campaigns/:id/world/equipment/weapons/:weaponId',
  WORLD_WEAPON_EDIT: '/campaigns/:id/world/equipment/weapons/:weaponId/edit',
  WORLD_ARMOR: '/campaigns/:id/world/equipment/armor',
  WORLD_ARMOR_NEW: '/campaigns/:id/world/equipment/armor/new',
  WORLD_ARMOR_ENTRY: '/campaigns/:id/world/equipment/armor/:armorId',
  WORLD_ARMOR_EDIT: '/campaigns/:id/world/equipment/armor/:armorId/edit',
  WORLD_GEAR: '/campaigns/:id/world/equipment/gear',
  WORLD_GEAR_NEW: '/campaigns/:id/world/equipment/gear/new',
  WORLD_GEAR_ENTRY: '/campaigns/:id/world/equipment/gear/:gearId',
  WORLD_GEAR_EDIT: '/campaigns/:id/world/equipment/gear/:gearId/edit',
  WORLD_MAGIC_ITEMS: '/campaigns/:id/world/equipment/magic-items',
  WORLD_MAGIC_ITEM_NEW: '/campaigns/:id/world/equipment/magic-items/new',
  WORLD_MAGIC_ITEM: '/campaigns/:id/world/equipment/magic-items/:magicItemId',
  WORLD_MAGIC_ITEM_EDIT: '/campaigns/:id/world/equipment/magic-items/:magicItemId/edit',
  WORLD_CLASSES: '/campaigns/:id/world/classes',
  WORLD_CLASS: '/campaigns/:id/world/classes/:classId',
  WORLD_CLASS_NEW: '/campaigns/:id/world/classes/new',
  WORLD_CLASS_EDIT: '/campaigns/:id/world/classes/:classId/edit',
  WORLD_RACES: '/campaigns/:id/world/races',
  WORLD_RACE_NEW: '/campaigns/:id/world/races/new',
  WORLD_RACE: '/campaigns/:id/world/races/:raceId',
  WORLD_RACE_EDIT: '/campaigns/:id/world/races/:raceId/edit',
} as const
