export type {
  ConditionConsequence,
  ConditionRule,
  MarkerRule,
  ActionLimitConsequence,
  MovementConsequence,
  AttackModConsequence,
  SaveModConsequence,
  CheckModConsequence,
  SpeechConsequence,
  AwarenessConsequence,
  VisibilityConsequence,
  CritWindowConsequence,
  SourceRelativeConsequence,
  DamageInteractionConsequence,
  BattlefieldAbsenceConsequence,
} from './condition-consequences.types'
export { CONDITION_RULES } from './condition-definitions'
export { ENGINE_STATE_RULES } from './engine-state-definitions'
export { ALL_MARKER_RULES } from './marker-rules'
export {
  getActiveConsequences,
  getActiveEngineStateRuleIds,
  hasBattlefieldAbsenceConsequence,
  getBattlefieldPresenceSkipReason,
  canTakeActions,
  canTakeReactions,
  getSpeedConsequences,
  getIncomingAttackModifiers,
  getOutgoingAttackModifiers,
  getIncomingAttackModifiersForAttack,
  getOutgoingAttackModifiersForAttack,
  shouldCountAttackModForAttackRoll,
  autoFailsSave,
  getSaveModifiersFromConditions,
  getDamageResistanceFromConditions,
  incomingHitBecomesCrit,
  getConditionSourceIds,
  hasConditionFromSource,
  getSourceRelativeRestrictions,
  cannotTargetWithHostileAction,
  canSpeak,
  isAwareOfSurroundings,
  canSee,
  getActiveConsequencesWithOrigin,
  type SourceRelativeRestriction,
  type ConsequenceWithOrigin,
} from './condition-queries'
