export { CombatLane } from './shared/CombatLane'
export { AllyRosterLane } from './shared/AllyRosterLane'
export { OpponentRosterLane } from './shared/OpponentRosterLane'
export { CombatantPreviewCard } from './shared/CombatantPreviewCard'
export { CombatLogEntryGroup } from './shared/CombatLogEntry'
export { TurnOrderList } from './active/TurnOrderList'
export type { TurnOrderEntry } from './active/TurnOrderList'
export { EncounterView } from './shared/EncounterView'
export { EncounterSetupView } from './setup/EncounterSetupView'
// EncounterActiveView removed -- replaced by grid-centric layout in EncounterActiveRoute
export { EncounterSetupHeader } from './setup/EncounterSetupHeader'
export { EncounterActiveHeader } from './active/EncounterActiveHeader'
export { EncounterActiveFooter } from './active/EncounterActiveFooter'
export type { InteractionMode } from './active/EncounterActiveFooter'
export type { GridInteractionMode } from '../domain/encounter-interaction.types'
export { EncounterEnvironmentSetup } from './setup/EncounterEnvironmentSetup'
export type { EnvironmentSetupValues } from './setup/EncounterEnvironmentSetup'
export { EncounterEnvironmentSummary } from './shared/EncounterEnvironmentSummary'
export { AllyCombatantSetupPreviewCard } from './setup/AllyCombatantSetupPreviewCard'
export { OpponentCombatantSetupPreviewCard } from './setup/OpponentCombatantSetupPreviewCard'
export { AllyCombatantActivePreviewCard } from './active/AllyCombatantActivePreviewCard'
export { OpponentCombatantActivePreviewCard } from './active/OpponentCombatantActivePreviewCard'
export { AllyActionDrawer } from './active/AllyActionDrawer'
export { OpponentActionDrawer } from './active/OpponentActionDrawer'
export { CombatantActionDrawer } from './shared/CombatantActionDrawer'
export type { CombatantStatBadge, CombatantTrackedPartBadge } from './shared/combatant-badges'
export {
  CombatantCoreBadgeRow,
  CombatantPreviewChipRow,
  CombatantStatBadgeRow,
  CombatantTrackedPartBadgeRow,
} from './shared/combatant-badges'
// CombatActionPreviewCard and CombatTargetPreviewCard removed -- replaced by CombatantActionDrawer
export { CombatLogPanel } from './active/CombatLogPanel'
export { EncounterActiveSidebar } from './active/EncounterActiveSidebar'
export { EncounterGrid } from './active/EncounterGrid'
export { EncounterGridSetup, GRID_SIZE_PRESETS } from './setup/EncounterGridSetup'
export type { GridSizePreset } from './setup/EncounterGridSetup'
export { ActionRow } from './shared/ActionRow/ActionRow'
export { ActionRowBase } from './shared/ActionRow/ActionRowBase'
export { WeaponActionRow } from './shared/ActionRow/WeaponActionRow'
export { SpellActionRow } from './shared/ActionRow/SpellActionRow'
export { NaturalActionRow } from './shared/ActionRow/NaturalActionRow'
export { EncounterEditModal } from './shared/EncounterEditModal'
export { CombatTargetSelectModal, buildTargetOptions } from './active/CombatTargetSelectModal'
export { CombatLogModal } from './active/CombatLogModal'
export { CombatTurnOrderModal } from './active/CombatTurnOrderModal'
export { SelectEncounterCombatantModal } from './setup/SelectEncounterCombatantModal'
export type { CombatantOption } from './setup/SelectEncounterCombatantModal'
export { SelectEncounterAllyModal } from './setup/SelectEncounterAllyModal'
export { SelectEncounterOpponentModal } from './setup/SelectEncounterOpponentModal'
